version: '3'
services:
  money-grtnr-ghost:
    image: ghost:3.8
    restart: always
    depends_on:
      - mysql-db
    environment:
      url: http://${MONEY_GRTNR_SERVER_URL:?err}
      database__client: mysql
      database__connection__host: mysql-db
      database__connection__user: root
      database__connection__password: ${MONEY_GRTNR_DB_PASS:?err}
      database__connection__database: money-ghost
      logging__path: /logs
      logging__info: 'info'
      mail__transport: 'SMTP'
      mail__from: '${MONEY_GRTNR_GMAIL_EMAIL:?err}'
      mail__options__service: 'gmail'
      mail__options__host: 'smtp.gmail.com'
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: '${MONEY_GRTNR_GMAIL_EMAIL:?err}'
      mail__options__auth__pass: '${MONEY_GRTNR_GMAIL_PASS:?err}'
    volumes:
      - ./money.grtnr/ghost_content:/var/lib/ghost/content
      - ./money.grtnr/ghost_logs:/logs

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MONEY_GRTNR_DB_PASS:?err}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  grtnr-ghost:
    image: ghost:3.8
    restart: always
    depends_on:
      - mysql-db
    environment:
      url: http://${GRTNR_SERVER_URL:?err}
      database__client: mysql
      database__connection__host: mysql-db
      database__connection__user: root
      database__connection__password: ${GRTNR_DB_PASS:?err}
      database__connection__database: grtnr-ghost
      logging__path: /logs
      logging__info: 'info'
      mail__transport: 'SMTP'
      mail__from: '${GRTNR_GMAIL_EMAIL:?err}'
      mail__options__service: 'gmail'
      mail__options__host: 'smtp.gmail.com'
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: '${GRTNR_GMAIL_EMAIL:?err}'
      mail__options__auth__pass: '${GRTNR_GMAIL_PASS:?err}'
    volumes:
      - ./grtnr.de/ghost_content:/var/lib/ghost/content
      - ./grtnr.de/ghost_logs:/logs

  nginx:
    image: nginx
    restart: always
    depends_on:
      - money-grtnr-ghost
      - grtnr-ghost
      - wiki
    ports:
      - '80:80'
      - '443:443'
    environment:
      MONEY_GRTNR_SERVER_URL: ${MONEY_GRTNR_SERVER_URL:?err}
      GRTNR_SERVER_URL: ${GRTNR_SERVER_URL:?err}
      WIKI_SERVER_URL: ${WIKI_SERVER_URL:?err}
    volumes:
      - ./nginx_html:/nginx_html:ro
      - ./nginx_conf:/etc/nginx
      - ./nginx_logs:/logs
    command: /bin/bash -c "envsubst  '$$WIKI_SERVER_URL\n$$ROOT_SERVER_URL\n$$MONEY_GRTNR_SERVER_URL\n$$GRTNR_SERVER_URL' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  wiki-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    #      logging:
    #        driver: 'none'
    restart: unless-stopped
    volumes:
      - ./wiki-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
